ustclug/mirrorhelp

help/kali.txt
test working on my kali linux 2.0
=> looks kali 2.0 need a different distro name.

help/alpinelinux.txt
=> add alpine linux help page

help/mariadb.txt
It costs me a lot of time to find out how to use USTC MariaDB mirror.
=> Add MariaDB mirror help

help/ubuntu.txt
As TUNA commented proposed repo, doing so on USTC's help document can avoid confusing.
Also rewrite several URL to HTTPS.
=> Comment ubuntu proposed repo, fix links.

source/brew.git.rst, source/homebrew-bottles.rst, source/homebrew-cask.git.rst, source/homebrew-core.git.rst, source/index.rst
=> Homebrew相关仓库

LICENSE.md
添加与DokuWiki相同的许可
除了原始Dokuwiki之外的文档贡献者：@zhsj @knight42 @gaoyifan
是否同意增加许可？（针对全新创作的文档）
=> add BY-NC-SA 4.0 LICENSE

source/epel.rst, source/index.rst, source/mariadb.rst
=> Add epel and mariadb

source/aosc.rst, source/index.rst
This PR adds AOSC OS（安同 OS）USTC mirror help to USTC LUG's wiki.
=> aosc: add AOSC OS mirror doc

source/index.rst, source/rpmfusion.rst
copy from https://lug.ustc.edu.cn/wiki/mirrors/help/rpmfusion
=> add rpmfusion

source/homebrew-core.git.rst
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update.sh
=> Fix reset URL

source/freebsd-ports.rst, source/index.rst
=> add freebsd-ports

source/freebsd.rst, source/index.rst
=> Add freebsd

source/debian.rst
https://www.debian.org/releases/
=> Update Debian stable version and codename

source/contributor.rst, source/elpa.rst, source/index.rst
=> Add doc for Emacs ELPA

source/lede.rst
Update sed line to reflect the merging of lede and openwrt.
Add tips for https.
=> Update LEDE/Openwrt instruction.

source/hackage.rst
related:
https://github.com/commercialhaskell/stack/issues/4870
https://docs.haskellstack.org/en/v1.9.3/yaml_configuration/#package-indices
=> Update hackage help

source/msys2.rst
=> MSYS2: Add content about mirrorlist.ucrt64

source/ubuntu-cloud-images.rst
=>  更新ubuntu-cloud-images

source/anthon.rst
The current AOSC OS apt-gen-list has been completely rewritten and the old usage is now obsolete, this Pull Request will update the apt-gen-list to the new usage
=> anthon: update help document

source/ghcup.rst, source/index.rst
=> ghcup: add

source/ghcup.rst
=> fix: ghcup mirror.ustc.* -> mirrors.ustc.*

source/clojars.rst, source/index.rst
你好，我按照 `CONTRIBUTION.md` 里的步骤添加了 `clojars.rst`。之后尝试运行 `make html` 得到
Warning, treated as error:
sphinx_rtd_theme (< 0.3.0) found. It will not be available since Sphinx-6.0
make: *** [Makefile:19: html] Error 2
我的机子上并没有安装 `sphinx_rtd_theme` 这个包。查询仓库里最低版本也是 1.0.0，我不知道这个错误是否影响，请审核，谢谢。
=> Add help for clojars

source/centos.rst
Signed-off-by: yewq <598439741@qq.com>
=> 更新收录架构和 CentOS 8 相关警告

source/rocky.rst
=> Add Rocky Linux 9 in rocky.rst

source/ubuntu.rst
=> 添加将HTTP替换为HTTPS的命令

source/index.rst, source/winget-source.rst
测试过程中遇到玄学错误 0x80073d1b（不仅镜像源存在，重新添加官方源也可能遇到），顺手记录了。
因为没有 Autotools 环境故没有本地编译过，但语法应该是正确的（应该）。
Related issue: https://github.com/ustclug/mirrorrequest/issues/275
=> Add help for winget source

source/freebsd-ports.rst
没有必要拉取整个项目，太大了。只做 `--depth 1` 即可
=> 减少 FreeBSD ports 拉取 git 目录的深度

source/gentoo-portage.rst, source/gentoo.git.rst, source/index.rst
=> 添加gentoo.git源的帮助文档

docs/debian-security.md, docs/debian.md, docs/ubuntu-ports.md, docs/ubuntu.md, includes/deb822.md
调整了 Ubuntu/Debian 相关的帮助写作（主要有关 DEB822 的部分）。
=> DEB822 说明更新

docs/openeuler.md
=> 添加了欧拉系统(openEuler)的镜像源替换方式

docs/winget-source.md
RT. Note that the doc has not been locally built and previewed.
=> Update WinGet doc to include SmartScreen bypass

docs/packaging-gitea.md
Feel free to point out any issues :)
=> packaging-gitea: Add documentation

docs/debian.md, docs/proxmox.md, includes/deb822.md, mkdocs.yml
=> debian, proxmox: add trixie and update deb822
