ustclug/mirrorhelp

- help/gentoo-portage.txt
should use repos.conf instead of SYNC
reference: https://wiki.gentoo.org/wiki/SYNC
Please check syntax! I am not familiar with LUG syntax. :)
> update gentoo-portage help

- help/brew.git.txt
- help/homebrew-core.git.txt
Update the Homebrew mirror setting doc due to the upstream change the dir of Homebrew repo.
The migrate issue is [here](https://github.com/Homebrew/brew/issues/987).
> fix(Homebrew): Update the Homebrew help doc for upstream change

- help/brew.git.txt
- help/homebrew-core.git.txt
1. Collect the Homebrew help doc in one place except bottle setting.
2. Replace the git to https for efficiency and security.
3. Add the reset method avoiding the ustc mirror break(It is git can't connect now).
4. Need review for the doc format after the transfer through tools.
> refactor(homebrew): Collect the help doc in one place

- help/archlinuxcn.txt
> since all packages are signed, default value for SigLevel (Required DatabaseOptional) is better. 
-- lilydjwg
see also: archlinuxcn/repo#218
> Remove siglevel from archlinuxcn mirror config

- source/dockerhub.rst
如果base URL是  `mirrors.u.e.c/dockerhub` ，则最终会访问 `mirrors.u.e.c/v2/xxxx`
因此需要在`mirrors.u.e.c/dockerhub` 后加一个`/`
> 修复dockerhub URL

- source/gentoo-portage.rst
- source/index.rst
- source/mageia.rst
1 新增 Mageia 源帮助文档。
2 出于强迫症原因，微调 Gentoo Portage 源使用帮助名称 (Debian Security 源使用帮助的名称里没有短横杠的)...
> 新增 Mageia 源帮助文档

- source/dockerhub.rst
Original address https://mirrors.ustc.edu.cn/dockerhub/  does not work because of  ValidateMirror function in https://github.com/moby/moby/blob/master/registry/config.go#L264, which came from commit 
https://github.com/moby/moby/commit/5b9348c553d183bc62f6e7cc8f934766fac162bd
SHOULD Use http://docker.mirrors.ustc.edu.cn/ directly
> Update dockerhub mirror address

- source/debian-multimedia.rst
使用Debian Multimedia 需要导入deb-multimedia-keyring，否则会报数字签名错误。
在Debian Multimedia 源使用帮助中添加导入deb-multimedia-keyring的操作说明。
> 在Debian Multimedia 源使用帮助中添加导入deb-multimedia-keyring的操作说明。

- source/ubuntu.rst
修改 ubuntu 帮助文档中 tips 的格式错误与里面的错别字。
> [fix] fix ubuntu tips format errors

- source/anaconda.rst
Some packages' updates such as pytorch are released in 'main' channel.
Adding this line in HOW-TO is useful.
> add a channel 'main' of conda

- source/index.rst
- source/nodesource.rst
如题。在[配置脚本没有提供之前](https://github.com/ustclug/mirrorrequest/issues/200)，提供手动配置软件源的帮助文档。
> 添加 nodesource 使用帮助

- source/anthon.rst
The following changes since commit ad7c895eec03d93af9acd6d9b853bd6fa5837ec8:
Rename to the repo name on mirrors (2018-09-28 10:57:42 +0800)
are available in the Git repository at:
https://github.com/AOSC-Dev/mirrorhelp 
for you to fetch changes up to 9a82cceeacc59fc1529516d039efbfe5355e5e80:
anthon: update mirror help text (2018-09-28 15:22:48 +0800)
----------------------------------------------------------------
Junde Yhi (1):
anthon: update mirror help text
source/anthon.rst | 46 ++++++----------------------------------------
1 file changed, 6 insertions(+), 40 deletions(-)
> anthon: update mirror help text

- source/brew.git.rst
这么写 `sed` 是因为 brew 的安装脚本中的变量名变了好几次，并且 brew 他们也不打算配置成可以使用环境变量配置上游的方式。与其跟着 brew 脚本里面改变量名一直改帮助，不如把 URL 直接替换掉……
不太清楚这么写合不合适，所以交个 PR 看看（
> brew.git: use git insteadOf to replace urls in install.sh

- source/brew.git.rst
- source/homebrew-bottles.rst
- source/linuxbrew-bottles.rst
参考[brew Release 3.0.7发布内容](https://github.com/Homebrew/brew/releases/tag/3.0.7)的参考，去除了对`/bottles`这级路径的拼接，因此目前得类似：`HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles/bottles`如此。
参考：
- [github_packages: fix HOMEBREW_BOTTLE_DOMAIN usage. ](https://github.com/Homebrew/brew/pull/10863)
> brew v3.0.7开始,HOMEBREW_BOTTLE_DOMAIN需要指定到/bottles这一级路径

- source/opensuse.rst
- source/packman.rst
主要改动如题，根据 [Wiki](https://en.opensuse.org/SDB:System_upgrade#5._Update_the_repos) 作如此替换，新装的系统中也是默认使用 `$releasever` 的。
另外 openSUSE 配置那里把 USTC:UPDATE-SLE 加上了。
另外由于 [Backports](https://mirrors.ustc.edu.cn/opensuse/update/leap/15.3/backports/) 是默认启用的，科大没有镜像这个仓库，在 openSUSE「注意事项」部分添加了说明。
> Note 1: openSUSE「图形界面下配置方法」部分的 Non-***OSS*** Repository 跟 Update Repository (Non-***Oss)*** 中的 OSS 大小写默认就是这样的。
> Note 2: 以上所有标有「默认」的地方均参照了 openSUSE-Leap-15.3-GNOME-Live-x86_64-Build9.108-Media.iso。
感谢抽出时间 review 这个 PR！
off-topic: [ustclug/opensuse-guide](https://github.com/ustclug/opensuse-guide) 可能需要更新一下。
> opensuse, packman: use $releasever in repository url 

- source/raspbian.rst
"5.1.3. Changed security archive layout
For bullseye, the security suite is now named bullseye-security instead of codename/updates and users should adapt their APT source-list files accordingly when upgrading.
The security line in your APT configuration may look like:
deb https://deb.debian.org/debian-security bullseye-security main contrib"
> fix debian 11 security archive layout

- source/nix-channels.rst
以下链接现在都重定向到 https://nixos.org/ 了：
- https://nixos.org/nix
- https://nixos.org/nixpkgs
同时修复了安装 Nix 的链接（NixOS/nix/pull/3857）。
> nix-channels: fix links

- source/raspbian-addons.rst
由于上游修改了存储库目录结构，这里也要作出相应的修改。
https://github.com/raspbian-addons/raspbian-addons/issues/109
> Update docs for raspbian-addons

- source/nix-channels.rst
- NixOS 19.03 及之前的版本都 [EOL 至少两年了](https://endoflife.date/nixos)，从示例配置中删除了 `"https://cache.nixos.org/"`。
- https://github.com/NixOS/nixpkgs/commit/4a9d9928dc01421b878cfe4a16961c1e4862d846 起 NixOS 配置 binary cache 就需要使用 `nix.settings.substituters` 了。
- nix-darwin [依然](https://github.com/LnL7/nix-darwin/blob/bb3baef6e115ae47bc2ab4973bd3a486488485b0/modules/nix/default.nix#L231-L238) 使用的是 `nix.binaryCaches`。
> nix-channels: add instructions for NixOS 22.05

- source/opensuse.rst
> Add command to configure Tumbleweed

- source/msys2.rst
https://github.com/msys2/MSYS2-packages/commit/cfdb662d9859a21174afa3c9c3d1eb9ec1d98727
MSYS2 pacman.conf 已经为 MinGW 相关仓库（mingw32、mingw64、ucrt64、clang64，以及此后添加的 clang32、clangarm64）使用统一的配置文件。
> Update msys2: unified mingw mirror list change

- source/archlinuxarm.rst
Arch Linux ARM 已停止支持 ARMv5 和 ARMv6，见 https://archlinuxarm.org/forum/viewtopic.php?f=3&t=15721
> Update archlinuxarm.rst, remove armv5 and armv6 architecture

- source/crates.io-index.rst
cargo 安装时，如果没有指定 CARGO_HOME 时，默认的 CARGO_HOME 路径为 `~/.cargo` cargo 的配置文件路径 `$CARGO_HOME/config.toml`, 但是如果用户配置了 CARGO_HOME 环境变量，则配置文件的路径不再是 `~/.cargo/config.toml`，详细内容参见： [The Cargo Book Configuration](https://doc.rust-lang.org/cargo/reference/config.html#configuration)
PR修正了文本中的路径（使用 `$CARGO_HOME/config.toml` 替换 `~/.cargo/config`，原本的配置文件没有`.toml`后缀，不确定之前的文档是否正确）。并增加了 Linux 环境下写入配置文件的命令。
> fix(crates.io-index): fix config file path error when install rust without default CARGO_HOME environment variable

- source/crates.io-index.rst
> fix(crates.io-index): command error

- source/raspberrypi.rst
1. bookworm 的默认源从 `http://archive.raspberrypi.org/` 更换为 `http://archive.raspberrypi.com/`
2. 从 bullseye 起不再提供 ui 仓库
> update to bookworm

- source/kali.rst
ref: https://www.kali.org/blog/non-free-firmware-transition/
Closes https://github.com/ustclug/discussions/issues/448
> fix/kali: add non-free-firmware

- source/nix-channels.rst
[上游: Many options moved/renamed from `nix.*` to `nix.settings.*`. For example
`nix.binaryCaches` is now `nix.settings.substituters`.
](https://github.com/LnL7/nix-darwin/blob/bcc8afd06e237df060c85bad6af7128e05fd61a3/CHANGELOG#L34-L35)
> 更正nix-darwin的文檔

- docs/mozilla.md
镜像源里只有amd64，所以`sources.list`里要加一个约束，主要是为了消除找不到i386包这种多余的报错
> mozilla - limit arch to amd64 only

- docs/archlinuxarm.md
The SSL certificate is only valid for the root domain `archlinuxarm.org`, when visiting `www.archlinuxarm.org` you'll get a warning.
> archlinuxarm: fix the link of home page

- docs/freebsd-pkg.md
Since currently there is no `SRV` record on either `_http._tcp.mirrors.ustc.edu.cn` or `_https._tcp.mirrors.ustc.edu.cn`, the `mirror_type` field in `/etc/pkg/FreeBSD.conf` should be overridden to `none`, otherwise `pkg(8)` may produce warnings like:
> pkg: No SRV record found for the repo 'FreeBSD'
See also: [pkg.conf(5)](https://man.freebsd.org/cgi/man.cgi?pkg.conf(5)), [#90665](https://forums.freebsd.org/threads/90655/), [#90716](https://forums.freebsd.org/threads/90716/)
> freebsd-pkg: add mirror_type: "none"

- docs/ghcup.md
当前版本的ghcup在安装时也会安装cabal，而如果只按照原本文档的内容做，此时的cabal并没有被设置科大镜像，因此会直接从官方网站走，下载量约100M，且没有很好的进度提示；
解决方案是按照hackage帮助中的内容设置cabal镜像；
我建议在ghcup的帮助中，建议读者阅读cabal镜像的帮助，并设置cabal镜像的代理；这部分文档的调整已经在这个PR中完成；
但是否采取这一方案，或是要重新组织文档的顺序，我认为有待讨论。
> update ghcup.md: inform users of the dependency of ghcup over hackage

- docs/openeuler.md
在 openEuler 22.03 (LTS-SP4) 或更早版本上，`repo.openeuler.org` 开始使用 https 协议。  
此 pr 修改了帮助文档中的 sed 命令，使其能够处理 `{http, https}://{repo, mirrors}.openeuler.org` 。
> openeuler: update sed command to handle HTTPS URLs

- docs/freebsd-pkg.md
Issue: https://github.com/ustclug/mirrorhelp/issues/290
> freebsd-pkg: Only older FreeBSD versions need `ca_root_nss` for HTTPS mirrors 
